import React from 'react';
import ReactDOM from 'react-dom';
import MainMessageForm from './MainMessageForm';

// TODO(MB) test autogenerated by generate-react-cli. Check if compatible with
// Jest (configured by create-react-app)

it('It should mount', () => {
  const div = document.createElement('div');
  ReactDOM.render(<MainMessageForm />, div);
  ReactDOM.unmountComponentAtNode(div);
});