import React from 'react';
import ReactDOM from 'react-dom';
import MainMessageForm, { MainMessageFormProps } from './MainMessageForm';
import { getEmptyTemplate } from '../../pages/MainMessage/MainMessage';

// TODO(MB) test autogenerated by generate-react-cli. Check if compatible with
// Jest (configured by create-react-app)

it('It should mount', () => {
  const div = document.createElement('div');
  const emptyTemplate = getEmptyTemplate();
  const mainMessageFormProps: MainMessageFormProps = {
    template: emptyTemplate,
    onAddMenuItemClicked: () => {},
    onMainHeaderChanged: () => {},
    onOpenMenuItem: () => {},
    onPrefillMainHeaderClicked: () => {},
    onSaveMainHeaderClicked: () => {},
  };
  ReactDOM.render(<MainMessageForm {...mainMessageFormProps} />, div);
  ReactDOM.unmountComponentAtNode(div);
});
