import React from 'react';
import ReactDOM from 'react-dom';
import LanguageSelector from './LanguageSelector';
import { Languages } from '../../i18n';

// TODO(MB) test autogenerated by generate-react-cli. Check if compatible with
// Jest (configured by create-react-app)

it('It should mount', () => {
  const div = document.createElement('div');
  ReactDOM.render(<LanguageSelector selectedLanguage={Languages.es} />, div);
  ReactDOM.unmountComponentAtNode(div);
});
